server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz_user_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
      idle-timeout: 60000
  
  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:your-client-id}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:your-client-secret}
            scope:
              - email
              - profile
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID:your-client-id}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET:your-client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

# Eureka 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

# 사용자 서비스 관련 설정
user:
  profile:
    default-image: https://example.com/default-profile.png
    upload-path: ${USER_UPLOAD_PATH:./uploads/profiles}
  account:
    verification-required: false
    verification-expiry: 24  # 시간
  password:
    min-length: 8
    require-special-char: true 