version: '3'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      
  # k6 서비스 - Caffeine 캐시 테스트용
  k6:
    image: grafana/k6:latest
    volumes:
      - ./:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb
    # 컨테이너가 계속 실행되도록 설정
    entrypoint: /bin/sh
    command: ["-c", "tail -f /dev/null"]
    # 컨테이너 내에서 명령어를 실행하려면:
    # docker-compose exec k6 k6 run /scripts/caffeine-cache-performance.js

volumes:
  influxdb-data:
  grafana-data: 