spring:
  # 개발 환경 데이터베이스 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서만 사용
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # 개발 환경 로깅 설정
  output:
    ansi:
      enabled: always

# 개발 환경 로깅 설정
logging:
  level:
    root: INFO
    com.quizplatform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# 개발 환경 actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"


# application.yml에 추가할 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 설정
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs  # API 문서 JSON 경로
  show-actuator: false  # Actuator 엔드포인트 문서화 비활성화
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**  # API 문서화할 경로 패턴