# 성능 최적화를 위한 애플리케이션 설정
# 운영 환경에서 사용할 수 있는 설정입니다.

spring:
  datasource:
    hikari:
      # 연결 타임아웃 증가
      connection-timeout: 30000  # 30초
      # 최대 연결 풀 크기 조정 (서버 사양 및 리소스에 맞게 조절)
      maximum-pool-size: 10
      # 연결 유지 시간 설정
      max-lifetime: 1800000  # 30분
      # 최소 유휴 연결 개수 설정
      minimum-idle: 5
      # 연결 테스트 쿼리 설정 (DB가 연결을 유지하는지 확인)
      connection-test-query: SELECT 1
      # 유휴 타임아웃 설정
      idle-timeout: 300000  # 5분
  
  jpa:
    properties:
      hibernate:
        # 배치 처리 최적화
        jdbc:
          batch_size: 50
        # N+1 문제 최소화를 위한 설정
        default_batch_fetch_size: 100
        # 쿼리 통계 활성화 (성능 튜닝을 위해)
        generate_statistics: false
        # 쿼리 로그 형식 설정
        format_sql: false
        # 영속성 컨텍스트 플러시 모드 최적화
        order_inserts: true
        order_updates: true
    
    # 영속성 컨텍스트 관리 설정
    open-in-view: false  # OSIV 비활성화로 DB 커넥션 사용 시간 단축
  
  # 캐시 관련 설정
  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
    type: caffeine

# 서버 설정
server:
  tomcat:
    # 최대 스레드 수 증가
    max-threads: 200
    # 연결 타임아웃 설정
    connection-timeout: 10000
    # 최대 연결 수
    max-connections: 10000
    # 압축 활성화로 네트워크 트래픽 감소
    compression:
      enabled: true
      min-response-size: 2048  # 2KB 이상 압축
  
  # 응답 압축 활성화
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048  # 2KB 이상 압축

# 로깅 설정
logging:
  level:
    # 운영 환경에서는 로깅 레벨 조정 
    org.hibernate.SQL: INFO  # 개발 환경에서는 DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # 개발 환경에서는 TRACE
    com.quizplatform: INFO  # 애플리케이션 로그 레벨
    
    # 캐시 관련 로깅 최적화
    com.quizplatform.core.aop.CaffeineCacheAspect: INFO
    com.quizplatform.core.controller.interceptor.CacheStatusInterceptor: INFO
    com.quizplatform.core.filter.ThreadLocalCleanupFilter: INFO
    org.springframework.cache: INFO
    
    # 성능 테스트 시에는 아래 주석 해제하여 더 엄격하게 설정
    # root: WARN
    # com.quizplatform: INFO

# 애플리케이션 커스텀 설정
quizplatform:
  # 성능 및 부하 관련 설정
  performance:
    # 인기 퀴즈 쿼리 처리 시 최대 결과 수 제한
    max-popular-quiz-results: 30
    # 퀴즈 추천 시 최대 처리 시간 (밀리초)
    recommendation-timeout-ms: 500
    # 비동기 처리를 위한 스레드 풀 설정
    async:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 25